"""added reminder_sent

Revision ID: 1311f8f8f071
Revises: ec20c41c335e
Create Date: 2026-06-16 17:58:38.873678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1311f8f8f071'
down_revision: Union[str, Sequence[str], None] = 'ec20c41c335e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'reminder_sent')
    # ### end Alembic commands ###
