"""remove is_completed

Revision ID: 660146a28ed3
Revises: dffe9cf51d93
Create Date: 2026-06-15 21:57:34.934699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660146a28ed3'
down_revision: Union[str, Sequence[str], None] = 'dffe9cf51d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
