"""added reminder_sent nullabe

Revision ID: d2792087ec9c
Revises: 1311f8f8f071
Create Date: 2026-06-16 18:31:45.246928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2792087ec9c'
down_revision: Union[str, Sequence[str], None] = '1311f8f8f071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tasks', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tasks', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
