"""add status and priority to tasks

Revision ID: dffe9cf51d93
Revises: dd5dda02b59d
Create Date: 2026-06-15 21:36:16.298560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffe9cf51d93'
down_revision: Union[str, Sequence[str], None] = 'dd5dda02b59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('status', sa.String(), nullable=True))
    op.add_column('user_tasks', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'priority')
    op.drop_column('user_tasks', 'status')
    # ### end Alembic commands ###
