"""added unique for usere

Revision ID: f2e662928f11
Revises: d2792087ec9c
Create Date: 2026-06-17 16:51:50.838182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e662928f11'
down_revision: Union[str, Sequence[str], None] = 'd2792087ec9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_table', ['username'])
    op.create_unique_constraint(None, 'user_table', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    # ### end Alembic commands ###
